// .aura/services/core/src/weaver_data/types_generator.ts
import path from 'path';

/**
 * 🧵 ДНК МОДУЛЯ WEAVER_TYPES: Декларативная генерация реестра компонентов в ОЗУ
 * На основе Cypher-записей Memgraph строит чистые интерфейсы и карту ComponentMap
 */
export function generateComponentTypesFile(validationProject: any, componentRecords: any[], targetSrcPath: string): any {
    let content = `// Auto-generated by Aura Weaver v14.6
export namespace SharedTypes {
  export interface AuraContext {
    world: any;
    deltaTime: number;
    tick: number;
    isLocalPlayer: boolean;
    getPlatformInputVector(): any;
    getBaseSpeed(archetype: string): number;
  }
`;

    // Динамически генерируем интерфейсы компонентов из нод Memgraph
    componentRecords.forEach(record => {
        const name = record.get('className');
        const astRaw = record.get('astJson') || "{}";
        
        let fieldsObj: Record<string, string> = {};
        try { 
            fieldsObj = JSON.parse(astRaw); 
        } catch(e) {
            // Если в ОЗУ прилетел чистый XML, парсим его поля по упрощенной схеме
            const fieldsMatch = astRaw.match(/fields=\{\{\s*([\s\S]*?)\s*\}\}/);
            if (fieldsMatch) {
                fieldsMatch[1].split(',').forEach((pair: string) => {
                    const [k, v] = pair.split(':').map(s => s.trim().replace(/['"]/g, ""));
                    if (k && v) fieldsObj[k] = v;
                });
            }
        }

        let interfaceContent = `  export interface ${name} {\n`;
        Object.entries(fieldsObj).forEach(([fieldName, fieldType]) => {
            interfaceContent += `    ${fieldName}: ${fieldType};\n`;
        });
        interfaceContent += `  }\n\n`;
        content += interfaceContent;
    });

    content += `
  export type ComponentMap = {
    ${componentRecords.map(r => `'${r.get('className')}': ${r.get('className')};`).join('\n    ')}
  };
}
`;

    const virtualPath = "src/shared/types/components.types.ts";
    const physicalPath = path.join(targetSrcPath, "shared/types/components.types.ts");
    
    return { 
        virtualFile: validationProject.createSourceFile(virtualPath, content, { overwrite: true }), 
        physicalPath 
    };
}