/**
 * ⚡ МОДЕРНИЗИРОВАННЫЙ СЛУЖЕБНЫЙ ПРОЦЕССОР ТИПИЗАЦИИ TS v38.9 (JULIA ACTIVE CONTOUR)
 * Склеивает модульнуюLEGO-матрицу с полной поддержкой боевых компонентов Damage и DamagePayload.
 */

import { tsSpawnRules } from './ts_rules/ts_spawn_rules';
import { tsMovementRules } from './ts_rules/ts_movement_rules'; 
import { tsDamageRules } from './ts_rules/ts_damage_rules';
import { tsGlobalMocks } from './ts_rules/ts_global_mocks';

// Динамически склеиваем матрицу типов из независимых файлов правил, страхуя боевой контур урона
export const globalMocksHeader = `// --- AURA RUNTIME TYPE EMBED CONTOUR v38.9 (JULIA SYNCHRONIZED MATRIX) ---
// Auto-generated by Aura Weaver Engine. Do not modify manually.

// 🔥 ФИКС: Внедрен сквозной импорт боевых компонентов DamageComponent и DamagePayloadComponent
import { 
  ArchetypeComponent, 
  VelocityComponent, 
  CFrameComponent, 
  WeaponStateComponent, 
  HealthComponent, 
  ExplosionTriggerComponent,
  DamageComponent,
  DamagePayloadComponent
} from "../../shared/components.types";

${tsMovementRules}
${tsSpawnRules}
${tsDamageRules}
${tsGlobalMocks}
`;
