// .aura/services/core/src/weaver_julia/ts_post_processor.ts
import { tsGlobalMocks } from './ts_rules/ts_global_mocks';

export const globalMocksHeader = `// --- AURA RUNTIME TYPE EMBED CONTOUR v38.9 (PURE NATIVE MATRIX) ---
// Auto-generated by Aura Weaver Engine. Do not modify manually.

import { 
  ArchetypeComponent, 
  VelocityComponent, 
  CFrameComponent, 
  WeaponStateComponent, 
  HealthComponent, 
  ExplosionTriggerComponent,
  DamageComponent,
  DamagePayloadComponent
} from "../../shared/components.types";

${tsGlobalMocks}
`;
