/**
 * ⚡ ДЕТЕРМИНИРОВАННЫЙ КОМПИЛЯТОР ТИПОВ ДЛЯ JULIA-СЛОВАРЕЙ v38.9 (ENTERPRISE)
 * Модуль отвечает за генерацию src/shared/components.types.ts из .jl паспорта.
 * Полная поддержка многострочных словарей Dict() и Union-литералов строк.
 */
export function compileJuliaComponentTypes(rawJuliaCode: string): string {
    let resultTs = `// --- AURA COMPONENTS PASSPORT TYPES v38.9 (JULIA ACTIVE CONTOUR) ---\n`;
    resultTs += `// Auto-generated by Aura Weaver Engine. Do not modify manually.\n\n`;
    
    try {
        // Вырезаем только тело словаря components = Dict( ... ) для защиты от внешнего шума
        const dictStart = rawJuliaCode.indexOf("components = Dict(");
        if (dictStart === -1) {
            throw new Error("В исходном коде паспорта отсутствует корневой словарь 'components = Dict('");
        }
        
        // Берем весь текст после открытия словаря компонентов
        const componentsBody = rawJuliaCode.substring(dictStart + "components = Dict(".length);
        
        // Регулярное выражение для снайперского извлечения блоков компонентов из текста
        // Ищет: "ИмяComponent" => Dict( ... мясо полей ... ) вне зависимости от переносов строк!
        const componentRegex = /"([A-Za-z0-9_]+Component)"\s*=>\s*Dict\(([\s\S]*?)\)(?=\s*,|\s*\))/g;
        
        let match;
        let foundAny = false;

        while ((match = componentRegex.exec(componentsBody)) !== null) {
            foundAny = true;
            const compName = match[1];
            const fieldsBlock = match[2];
            
            resultTs += `export interface ${compName} {\n`;
            
            // Парсим поля внутри блока Dict компонента line-by-line
            const fieldLines = fieldsBlock.split(/\r?\n/);
            for (let fLine of fieldLines) {
                let trimmedField = fLine.trim();
                if (!trimmedField || trimmedField.startsWith("#")) continue;
                
                // Ищем стрелочку "имя_поля" => "тип_данных"
                if (trimmedField.includes("=>")) {
                    const pair = trimmedField.split("=>");
                    if (pair.length >= 2) {
                        // Ключ очищаем от кавычек и пробелов
                        const fName = pair[0].replace(/["'\s]/g, "");
                        
                        // Тип данных очищаем только от внешних кавычек по краям (чтобы сохранить Union-литералы строк в кавычках!)
                        let fType = pair[1].trim().replace(/,$/, "").trim(); // Сносим запятую на конце строки Джулии
                        fType = fType.replace(/^["']|["']$/g, "").trim(); // Сносим внешние кавычки типа
                        
                        resultTs += `    ${fName}: ${fType};\n`;
                    }
                }
            }
            
            resultTs += `}\n\n`;
        }

        if (!foundAny) {
            throw new Error("Парсер не смог локализовать ни одной структуры компонента. Проверьте синтаксис словарей.");
        }
        
    } catch (e: any) {
        console.error(`[Aura Weaver Error] Крах компилятора типов: ${e.message}`);
        resultTs += `// ❌ КРИТИЧЕСКИЙ СБОЙ КОМПИЛЯЦИИ JULIA-СЛОВАРЯ: ${e.message}\n`;
    }
    
    return resultTs;
}
